# [general]
# import = [
#     "~/.config/alacritty/themes/themes/nordic.toml"
# ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 4
padding.y = 4
decorations = "None"
opacity = 0.82
blur = true

[colors.primary]
background = "0x080808"
foreground = "0xfbf1c7"

[colors.selection]
background = "0xdc3232"
text = "0xffffff"

[colors.cursor]
text = "#1F1F28"
cursor = "#6580A8"

[cursor.style]
blinking = "always"
shape = "Beam"
[cursor]
blink_interval = 450

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
