# general.import = ["~/.config/alacritty/theme/nordic.toml"]
# import = ["~/.config/alacritty/themes/themes/tomorrow_night.toml"]
# import = ["~/.config/alacritty/themes/themes/horizon-dark.toml"]
general.import = ["~/.config/alacritty/themes/themes/Rose-Pine.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]


[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"


[window]
dynamic_padding = true
dimensions = { columns = 250, lines = 90 }
option_as_alt = "OnlyRight"
# opacity = 0.92
blur = true
padding = { x = 8, y = 12 }
decorations = "None"
# decorations = "Transparent"
# decorations = "Buttonless"
class = { instance="Alacritty", general="Alacritty" }
resize_increments = true
position = "None"
decorations_theme_variant = "Dark"


[font]
builtin_box_drawing = true
# normal = { family = "SF Mono", style = "Regular" }
normal = { family = "SauceCodePro Nerd Font", style = "Italic" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 450

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "Z", mods = "Command", action = "ToggleSimpleFullscreen" },
{ key = "Right", mods = "Alt", chars = "\u001BF" },
{ key = "Left",  mods = "Alt", chars = "\u001BB" },
]
