# import = ["~/.config/alacritty/theme/nordic.toml"]
# import = ["~/.config/alacritty/theme/catppuccin-mocha.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
import = ["~/.config/alacritty/themes/themes/nordic.toml"]
shell = "/bin/zsh"


[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"


[window]
  dimensions = { columns = 140, lines = 48 }
  option_as_alt = "OnlyRight"
  opacity = 0.95
  blur = true
  padding = { x = 12, y = 12 }
  dynamic_padding = true
  # decorations = "None"
  # decorations = "Buttonless"
  dynamic_title = true
  class = { instance="Alacritty", general="Alacritty" }
  resize_increments = true
  position = "None"


[font]
  # normal = { family = "Iosevka Nerd Font", style = "Italic" }
  normal = { family = "PlemolJP35 Console NF", style = "Italic" }
  size = 11.25

[cursor]
  style = { shape = "Beam", blinking = "Always" }
  blink_interval=450

[mouse]
  hide_when_typing = true

[selection]
  save_to_clipboard=true

[keyboard]
bindings = [
{ key = "Z", mods = "Command", action = "ToggleSimpleFullscreen" },
# { key = "S", mods = "Command", chars = 'l' }
]
